##################################################################################
# COSC1283/1284 - Programming Techniques
# Semester 1 2010 Assignment #2 - SCSIT Program Management System
# Full Name        : EDIT HERE
# Student Number   : EDIT HERE
# Yallara Username : EDIT HERE
# Course Code      : EDIT HERE
# Program Code     : EDIT HERE
# Start up code provided by Christopher Hoobin, John Thangarajah, and Xiaodong Li
##################################################################################

# Delete this comment and insert your code here. bcheck

pms:  
	gcc -gstabs -Wall -ansi -pedantic pms.c pms_options.c pms_utility.c -o pms

clean:
	rm -rf *.o core pms *.zip


