import java.io.*;
import java.sql.*;

public class Front 
{
	public static void main(String args[]) throws SQLException 
	{

		try 
		{
			/**
			 * The following should connect to a MYSQL database.
			 * To establish a connection to the database an adress and available
			 * port number need to be substituted where 'localhost:3306'
			 * followed by a '/' and the database name.
			 * 
			 * To connect to the database the username and password 'root'
			 * need to be changed to the correct username and password
			 * (format is (connectionUrl,username,password)).
			 */
			Class.forName("com.mysql.jdbc.Driver");
			String connectionUrl = "jdbc:sqlserver://localhost:3306/database.sql";
			Connection con = DriverManager.getConnection(connectionUrl,"root","root");
			Statement s = con.createStatement();
			
			/**
			 * Once connected to the database the following queries
			 * should run. The first obtains the supplier name along
			 * with the part name.
			 * The next query gets the part name and the cost and then
			 * arranges them in order by cost from highest to lowest.
			 */
			ResultSet r = s.executeQuery("SELECT suppliers.name, supplier_parts.part_name FROM suppliers, supplier_parts" +
										 "WHERE suppliers.supplier_id = supplier_parts.supplier_id");
			ResultSet r2 = s.executeQuery("SELECT part_name, cost_in_cents FROM supplier_parts" +
										  "ORDER BY cost_in_cents ASC");
			
			String[] name = null;
			String[] part_name = null;
			String[] part_name2 = null;
			String[] price = null;
			
			int l = 0;
			/**
			 * The following 'while' loop should grab the 'name'
			 * and 'part name' generated by the SQL query and place
			 * them into the relevant arrays.
			 */
			while (r.next()) 
			{
				name[l] = r.getString(1);
				part_name[l] = r.getString(2);
				l++;
			}
			while (r2.next()) 
			{
				part_name2[l] = r.getString(1);
				price[l] = r.getString(2);
				l++;
			}
			
			/**
			 * The following code prints the data in the XML format.
			 */
			PrintWriter out = new PrintWriter(new FileOutputStream("result.xml"));
			out.println("<?xml version=\"1.0\" ?>");
			out.println("<!DOCTYPE SUPPLIERS SYSTEM \"users.dtd\">");
			out.println("<SUPPLIERS>");
			for (int i=0;i<name.length;i++)
			{
			  out.println("<SUPPLIER NAME=\""+name[i]+"\">"+part_name[i]+"</SUPPLIER>");
			}
			out.println("</SUPPLIERS>");
			
			out.println("<SUPPLIERS>");
			for (int i=0;i<name.length;i++)
			{
			  out.println("<SUPPLIER><PART NAME=\""+part_name[i]+"\"><COST>"+price[i]+"</SUPPLIER>");
			}
			out.println("</SUPPLIERS>");
			
			
			
			
			/**
			 * Closes the connection to the database.
			 */
			con.close();
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		} 
		catch (ClassNotFoundException e) 
		{
			e.printStackTrace();
		} 
		catch (FileNotFoundException e) 
		{
			e.printStackTrace();
		}
	
	}
}
