#################################################################################
# COSC1283/1284 - Programming Techniques
# Semester 1 2010 Assignment #1
# Full Name        : Lachlan Myers
# Student Number   : s3167356
# Yallara Username : s3167356
# Course Code      : COSC1284
# Program Code     : BP094
# Start up code provided by Christopher Hoobin, John Thangarajah, and Xiaodong Li
#################################################################################

# Delete this comment and insert your code here.

main.exe:  
	gcc -Wall -ansi -pedantic assign1.c assign1.h options1.c utility1.c -o assign1

clean:
	rm -rf *.o core assign1 *.zip
